#Site Settings
title: HaCkEr InDiA | A Ethical Hacking Page
description: "A minimal webpage template build with HTML5 , CSS, Javascript & PHP"
url: https://www.hackerindia.ml
author:
    name: "Yogesh Kumar Jamre"
    email: "yogeshkuamrjamre1@gmail.com"
    url: "https://www.hackerindia.ml"

#Build Settings
baseurl: https://www.hackerindia.ml
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 2
paginate_path: /page:num/

#Custom Variables
version: "1.1.0"

#Options
custom_header: false
custom_nav_footer: false
reverse: false

gems:
  - jekyll-sitemap
plugins:
  - jekyll-sitemap


